CREATE TABLE USERS (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 EMAIL VARCHAR(100) UNIQUE NOT NULL,
 USERNAME VARCHAR(50) UNIQUE NOT NULL,
 PASSWORD VARCHAR(255) NOT NULL,
 IS_ADMIN BOOLEAN
);

CREATE TABLE CLIPBOARDS (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 CLIPBOARD_NAME VARCHAR(100) UNIQUE NOT NULL,
 TYPES VARCHAR(255) NOT NULL,
 IS_PRIVATE BOOLEAN
);

CREATE TABLE SUBSCRIPTIONS (
 USER_ID INT NOT NULL,
 CLIPBOARD_ID INT NOT NULL,
 FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
 FOREIGN KEY (CLIPBOARD_ID) REFERENCES CLIPBOARDS(ID)
);

CREATE TABLE NOTIFICATIONS (
 USER_ID INT NOT NULL,
 CLIPBOARD_ID INT NOT NULL,
 COUNT INT,
 FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
 FOREIGN KEY (CLIPBOARD_ID) REFERENCES CLIPBOARDS(ID)
);

CREATE TABLE RESOURCE_TEXT (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 CLIPBOARD_ID INT NOT NULL,
 DESCRIPTION VARCHAR(255),
 CONTENT TEXT NOT NULL
);

CREATE TABLE RESOURCE_LINK (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 CLIPBOARD_ID INT NOT NULL,
 DESCRIPTION VARCHAR(255),
 CONTENT VARCHAR(255) NOT NULL
);

CREATE TABLE RESOURCE_IMAGE (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 CLIPBOARD_ID INT NOT NULL,
 DESCRIPTION VARCHAR(255),
 CONTENT LONGBLOB NOT NULL
);

CREATE TABLE RESOURCE_PDF (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 CLIPBOARD_ID INT NOT NULL,
 DESCRIPTION VARCHAR(255),
 CONTENT LONGTEXT NOT NULL
);

CREATE TABLE RESOURCE_PHP (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 CLIPBOARD_ID INT NOT NULL,
 DESCRIPTION VARCHAR(255),
 CONTENT TEXT NOT NULL
);

CREATE TABLE RESOURCE_HTML (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 CLIPBOARD_ID INT NOT NULL,
 DESCRIPTION VARCHAR(255),
 CONTENT TEXT NOT NULL
);

CREATE TABLE RESOURCE_CSS (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 CLIPBOARD_ID INT NOT NULL,
 DESCRIPTION VARCHAR(255),
 CONTENT TEXT NOT NULL
);

CREATE TABLE RESOURCE_JS (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 CLIPBOARD_ID INT NOT NULL,
 DESCRIPTION VARCHAR(255),
 CONTENT TEXT NOT NULL
);

CREATE TABLE RESOURCE_JSON (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 CLIPBOARD_ID INT NOT NULL,
 DESCRIPTION VARCHAR(255),
 CONTENT TEXT NOT NULL
);


INSERT INTO USERS (EMAIL, USERNAME, PASSWORD, IS_ADMIN)
VALUES 
    ('ivan_ivanov@abv.bg', 'Ivan Ivanov', 'ivanivanov', true),
    ('petar_petrov@abv.bg', 'Petar Petrov', 'petarpetrov', false),
    ('georgi_georgiev@abv.bg', 'Georgi Georgiev', 'georgigeorgiev', false);

INSERT INTO CLIPBOARDS (CLIPBOARD_NAME, TYPES, IS_PRIVATE)
VALUES
    ('clip1', 'text, link', false),
    ('clip2', 'image', true);

INSERT INTO SUBSCRIPTIONS (USER_ID, CLIPBOARD_ID)
VALUES
    (1, 1),
    (3, 2);

INSERT INTO NOTIFICATIONS (USER_ID, CLIPBOARD_ID, COUNT)
VALUES
    (1, 1, 2),
    (3, 2, 3);

INSERT INTO RESOURCE_TEXT (CLIPBOARD_ID, DESCRIPTION, CONTENT)
VALUES
    (1, "nqkuv tekst", "uuuuuuuuuuuuuuuuu aaaaaaaaaaaaaaaaa");

INSERT INTO RESOURCE_LINK (CLIPBOARD_ID, DESCRIPTION, CONTENT)
VALUES
    (1, "nqkuv link", "google.com");