CREATE TABLE USERS (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 EMAIL VARCHAR(100) UNIQUE NOT NULL,
 USERNAME VARCHAR(50) UNIQUE NOT NULL,
 PASSWORD VARCHAR(255) NOT NULL,
 IS_ADMIN BOOLEAN
);

CREATE TABLE CLIPBOARDS (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 CLIPBOARD_NAME VARCHAR(100) UNIQUE NOT NULL,
 TYPES VARCHAR(255) NOT NULL,
 IS_PRIVATE BOOLEAN
);

CREATE TABLE SUBSCRIPTIONS (
 USER_ID INT NOT NULL,
 CLIPBOARD_ID INT NOT NULL,
 FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
 FOREIGN KEY (CLIPBOARD_ID) REFERENCES CLIPBOARDS(ID)
);

CREATE TABLE NOTIFICATIONS (
 USER_ID INT NOT NULL,
 CLIPBOARD_ID INT NOT NULL,
 COUNT INT,
 FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
 FOREIGN KEY (CLIPBOARD_ID) REFERENCES CLIPBOARDS(ID)
);

CREATE TABLE RESOURCE_TEXT (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 CLIPBOARD_ID INT NOT NULL,
 DESCRIPTION VARCHAR(255),
 CONTENT TEXT NOT NULL
);

CREATE TABLE RESOURCE_LINK (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 CLIPBOARD_ID INT NOT NULL,
 DESCRIPTION VARCHAR(255),
 CONTENT VARCHAR(255) NOT NULL
);

CREATE TABLE RESOURCE_IMAGE (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 CLIPBOARD_ID INT NOT NULL,
 DESCRIPTION VARCHAR(255),
 CONTENT VARCHAR(255) NOT NULL
);

CREATE TABLE RESOURCE_PDF (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 CLIPBOARD_ID INT NOT NULL,
 DESCRIPTION VARCHAR(255),
 CONTENT VARCHAR(255) NOT NULL
);

CREATE TABLE RESOURCE_PHP (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 CLIPBOARD_ID INT NOT NULL,
 DESCRIPTION VARCHAR(255),
 CONTENT TEXT NOT NULL
);

CREATE TABLE RESOURCE_HTML (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 CLIPBOARD_ID INT NOT NULL,
 DESCRIPTION VARCHAR(255),
 CONTENT TEXT NOT NULL
);

CREATE TABLE RESOURCE_CSS (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 CLIPBOARD_ID INT NOT NULL,
 DESCRIPTION VARCHAR(255),
 CONTENT TEXT NOT NULL
);

CREATE TABLE RESOURCE_JS (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 CLIPBOARD_ID INT NOT NULL,
 DESCRIPTION VARCHAR(255),
 CONTENT TEXT NOT NULL
);

CREATE TABLE RESOURCE_JSON (
 ID INT PRIMARY KEY AUTO_INCREMENT,
 CLIPBOARD_ID INT NOT NULL,
 DESCRIPTION VARCHAR(255),
 CONTENT TEXT NOT NULL
);


INSERT INTO USERS (EMAIL, USERNAME, PASSWORD, IS_ADMIN)
VALUES 
    ('ivan_ivanov@abv.bg', 'Ivan Ivanov', 'ivanivanov', true),
    ('petar_petrov@abv.bg', 'Petar Petrov', 'petarpetrov', false),
    ('georgi_georgiev@abv.bg', 'Georgi Georgiev', 'georgigeorgiev', false);

INSERT INTO CLIPBOARDS (CLIPBOARD_NAME, TYPES, IS_PRIVATE)
VALUES
    ('clip1', 'text, link', false),
    ('clip2', 'image', false),
    ('clip3', 'js, php, pdf', false),
    ('clip4', 'html, css, json', true);

INSERT INTO SUBSCRIPTIONS (USER_ID, CLIPBOARD_ID)
VALUES
    (2, 1),
    (2, 2),
    (3, 1),
    (3, 3),
    (3, 4);

INSERT INTO NOTIFICATIONS (USER_ID, CLIPBOARD_ID, COUNT)
VALUES
    (2, 1, 2),
    (3, 3, 1);

INSERT INTO RESOURCE_TEXT (CLIPBOARD_ID, DESCRIPTION, CONTENT)
VALUES
    (1, "some placeholder text", "lorem ipsum dolor sit amet"),
    (1, "unique text", "unique");

INSERT INTO RESOURCE_LINK (CLIPBOARD_ID, DESCRIPTION, CONTENT)
VALUES
    (1, "link to google", "https://www.google.com"),
    (1, "FMI Web Site", "https://www.fmi.uni-sofia.bg/en");

INSERT INTO RESOURCE_JS (CLIPBOARD_ID, DESCRIPTION, CONTENT)
VALUES
    (3, "generates random integer", "function generateRandomInteger(max) {
    return Math.floor(Math.random() * max) + 1;
}"),
    (3, "alerts", "alert('Hello! I am an alert box!!');");

INSERT INTO RESOURCE_PHP (CLIPBOARD_ID, DESCRIPTION, CONTENT)
VALUES
    (3, "hello world on PHP", "<?php echo 'Hello World'; ?>"),
    (3, "Get system information from PHP", "<?php phpinfo(); ?>");

INSERT INTO RESOURCE_HTML (CLIPBOARD_ID, DESCRIPTION, CONTENT)
VALUES
    (4, "hello world page", "<html>
 <head>
  <title>Hello world</title>
 </head>
 <body>
 <p class='hello'>Hello World</p>
 </body>
</html>");

INSERT INTO RESOURCE_CSS (CLIPBOARD_ID, DESCRIPTION, CONTENT)
VALUES
    (4, "style for hello world paragraph", ".hello { margin-top: 3%; font-size: 16px; }");